CREATE TABLE QAHUB_QSTN (
	QSTN_ID			VARCHAR2(32),
	CTLG_ID			VARCHAR2(32),
	CTLG_NAME		VARCHAR2(50),
	SUBCTLG_ID		VARCHAR2(32),
	SUBCTLG_NAME	VARCHAR2(50),
	USER_ID			VARCHAR2(50) NOT NULL,
	TITLE			VARCHAR2(200) NOT NULL,
	CONTENT			VARCHAR2(4000),
	ATTMNT			BLOB,
	AVG_RAT			NUMBER(2,1) 	DEFAULT 0,
	STATUS			VARCHAR2(1)		DEFAULT '0',
	REPLY_NO		NUMBER(10,0)	DEFAULT	0,	
	ENT_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	UPD_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	ENT_TMS			TIMESTAMP	DEFAULT SYSTIMESTAMP,
	UPD_TMS			TIMESTAMP	DEFAULT	SYSTIMESTAMP,
	CONSTRAINT		PK_QAHUB_QSTN PRIMARY KEY (QSTN_ID)
);

CREATE TABLE QAHUB_ANS(
	QSTN_ID			VARCHAR2(32) NOT NULL,
	ANS_ID			VARCHAR2(32),
	USER_ID			VARCHAR2(20) NOT NULL,
	TITLE			VARCHAR2(200),
	CONTENT			VARCHAR2(4000),
	RATING			NUMBER(1,0)		DEFAULT 0,
	ENT_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	UPD_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	ENT_TMS			TIMESTAMP	DEFAULT SYSTIMESTAMP,
	UPD_TMS			TIMESTAMP	DEFAULT SYSTIMESTAMP,
	CONSTRAINT		PK_QAHUB_ANS	PRIMARY KEY (ANS_ID)
);

CREATE TABLE QAHUB_CTLG(
	CTLG_ID			VARCHAR2(32),
	CTLG_NAME		VARCHAR2(50) NOT NULL,
	ENT_TMS			TIMESTAMP	DEFAULT SYSTIMESTAMP,
	CONSTRAINT		PK_QAHUB_CTLG	PRIMARY KEY (CTLG_ID)

);

CREATE TABLE QAHUB_SUBCTLG(
	SUBCTLG_ID		VARCHAR2(32),
	CTLG_ID			VARCHAR2(32) NOT NULL,
	SUBCTLG_NAME	VARCHAR2(50) NOT NULL,
	ENT_TMS			TIMESTAMP DEFAULT SYSTIMESTAMP,
	CONSTRAINT 		PK_QAHUB_SUBCTLG	PRIMARY KEY (SUBCTLG_ID)
);