DROP TABLE QAHUB_QSTN;
DROP TABLE QAHUB_QSTN_DTL;
DROP TABLE QAHUB_ANS;
DROP TABLE QAHUB_ANS_DTL;
DROP TABLE QAHUB_CTLG;
DROP TABLE QAHUB_SUBCTLG;

CREATE TABLE QAHUB_QSTN (
	QSTN_ID			VARCHAR2(32),
	CTLG_ID			VARCHAR2(32),
	SUBCTLG_ID		VARCHAR2(32),
	USER_ID			VARCHAR2(20)	NOT NULL,
	TITLE			VARCHAR2(90)	NOT NULL,
	CONTENT			VARCHAR2(4000),
	ATTMNT			BLOB,
	STATUS			VARCHAR2(1)		DEFAULT	'0',
	REPLY_NO		NUMBER(5,0)		DEFAULT	0,
	DEL_FLAG		VARCHAR2(1)		DEFAULT	'0',
	ENT_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	UPD_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	ENT_TMS			TIMESTAMP		DEFAULT	SYSTIMESTAMP,
	UPD_TMS			TIMESTAMP		DEFAULT	SYSTIMESTAMP,
	CONSTRAINT	PK_QAHUB_QSTN PRIMARY KEY (QSTN_ID)
);

CREATE TABLE QAHUB_QSTN_DTL (
	QSTN_SEQ		VARCHAR2(32),
	QSTN_ID			VARCHAR2(32),
	CTLG_ID			VARCHAR2(32),
	SUBCTLG_ID		VARCHAR2(32),
	USER_ID			VARCHAR2(20)	NOT NULL,
	TITLE			VARCHAR2(90)	NOT NULL,
	CONTENT			VARCHAR2(4000),
	ATTMNT			BLOB,
	STATUS			VARCHAR2(1),
	CTL_FLAG		VARCHAR2(1)		DEFAULT	'0',
	ENT_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	ENT_TMS			TIMESTAMP		DEFAULT	SYSTIMESTAMP,
	CONSTRAINT		PK_QAHUB_QSTN_DTL PRIMARY KEY (QSTN_ID)
);

CREATE TABLE QAHUB_ANS(
	QSTN_ID			VARCHAR2(32)	NOT NULL,
	ANS_ID			VARCHAR2(32),
	USER_ID			VARCHAR2(20)	NOT NULL,
	CONTENT			VARCHAR2(4000),
	VOTE			NUMBER(1,0)		DEFAULT	0,
	DEL_FLAG		VARCHAR(1)		DEFAULT	'0',
	ENT_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	UPD_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	ENT_TMS			TIMESTAMP		DEFAULT	SYSTIMESTAMP,
	UPD_TMS			TIMESTAMP		DEFAULT	SYSTIMESTAMP,
	CONSTRAINT	  PK_QAHUB_ANS	PRIMARY KEY (ANS_ID)
);

CREATE TABLE QAHUB_ANS_DTL(
	QSTN_SEQ		VARCHAR2(32),
	QSTN_ID			VARCHAR2(32)	NOT NULL,
	ANS_ID			VARCHAR2(32),
	USER_ID			VARCHAR2(20)	NOT NULL,
	CONTENT			VARCHAR2(4000),
	CTL_FLAG		VARCHAR2(1)		DEFAULT	'0',
	ENT_DT			VARCHAR2(16)	DEFAULT	TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI'),
	ENT_TMS			TIMESTAMP		DEFAULT	SYSTIMESTAMP,
	CONSTRAINT		PK_QAHUB_ANS_DTL	PRIMARY KEY (ANS_ID)
);

CREATE TABLE QAHUB_CTLG(
	CTLG_ID			  VARCHAR2(32),
	CTLG_NAME		  VARCHAR2(50)	NOT NULL,
	ENT_TMS			  TIMESTAMP		DEFAULT SYSTIMESTAMP,
	CONSTRAINT	  PK_QAHUB_CTLG	PRIMARY KEY (CTLG_ID)
);

CREATE TABLE QAHUB_SUBCTLG(
	SUBCTLG_ID	  VARCHAR2(32),
	CTLG_ID			  VARCHAR2(32)	NOT NULL,
	SUBCTLG_NAME  VARCHAR2(50)	NOT NULL,
	ENT_TMS			  TIMESTAMP		DEFAULT SYSTIMESTAMP,
	CONSTRAINT		PK_QAHUB_SUBCTLG	PRIMARY KEY (SUBCTLG_ID)
);
