CREATE OR REPLACE PACKAGE PCKG_QAHUB_BATCH AS 

  PROCEDURE BATCH_CTLG;
  PROCEDURE BATCH_QSTN;
  PROCEDURE BATCH_ANS;

END PCKG_QAHUB_BATCH;
/


CREATE OR REPLACE PACKAGE BODY PCKG_QAHUB_BATCH AS

  PROCEDURE BATCH_CTLG AS
  
    V_CTLG_ID VARCHAR2(32);
    
  BEGIN
    INSERT INTO QAHUB_CTLG (CTLG_ID, CTLG_NAME) VALUES(SYS_GUID,'Java');
    INSERT INTO QAHUB_CTLG (CTLG_ID, CTLG_NAME) VALUES(SYS_GUID,'Python');
    INSERT INTO QAHUB_CTLG (CTLG_ID, CTLG_NAME) VALUES(SYS_GUID,'Ruby');

    SELECT CTLG_ID INTO V_CTLG_ID
      FROM QAHUB_CTLG WHERE CTLG_NAME = 'Java';
    
    INSERT INTO QAHUB_SUBCTLG (CTLG_ID,SUBCTLG_ID, SUBCTLG_NAME)
      VALUES(V_CTLG_ID, SYS_GUID, 'JDBC');
    INSERT INTO QAHUB_SUBCTLG (CTLG_ID,SUBCTLG_ID, SUBCTLG_NAME)
      VALUES(V_CTLG_ID, SYS_GUID, 'J2EE');
    INSERT INTO QAHUB_SUBCTLG (CTLG_ID,SUBCTLG_ID, SUBCTLG_NAME)
      VALUES(V_CTLG_ID, SYS_GUID, 'Spring');

    SELECT CTLG_ID INTO V_CTLG_ID
      FROM QAHUB_CTLG WHERE CTLG_NAME = 'Python';
    
    INSERT INTO QAHUB_SUBCTLG (CTLG_ID,SUBCTLG_ID, SUBCTLG_NAME)
      VALUES(V_CTLG_ID, SYS_GUID, 'Django');
    INSERT INTO QAHUB_SUBCTLG (CTLG_ID,SUBCTLG_ID, SUBCTLG_NAME)
      VALUES(V_CTLG_ID, SYS_GUID, 'Grok');
    INSERT INTO QAHUB_SUBCTLG (CTLG_ID,SUBCTLG_ID, SUBCTLG_NAME)
      VALUES(V_CTLG_ID, SYS_GUID, 'Pylons');

    SELECT CTLG_ID INTO V_CTLG_ID
      FROM QAHUB_CTLG WHERE CTLG_NAME = 'Ruby';
    
    INSERT INTO QAHUB_SUBCTLG (CTLG_ID,SUBCTLG_ID, SUBCTLG_NAME)
      VALUES(V_CTLG_ID, SYS_GUID, 'Rails');
    INSERT INTO QAHUB_SUBCTLG (CTLG_ID,SUBCTLG_ID, SUBCTLG_NAME)
      VALUES(V_CTLG_ID, SYS_GUID, 'Gem');

    NULL;
  END BATCH_CTLG;

  PROCEDURE BATCH_QSTN AS
    V_CTLG_ID       VARCHAR2(32);
    V_SUBCTLG_ID    VARCHAR2(32);
    V_CTLG_NAME     VARCHAR2(32);
    V_SUBCTLG_NAME  VARCHAR2(32);
  
  BEGIN
    FOR LOOP_INDEX IN 1..50 LOOP
      SELECT CTLG_ID, CTLG_NAME, SUBCTLG_ID, SUBCTLG_NAME
      INTO V_CTLG_ID, V_CTLG_NAME, V_SUBCTLG_ID, V_SUBCTLG_NAME
        FROM(
          SELECT QAHUB_SUBCTLG.CTLG_ID,QAHUB_CTLG.CTLG_NAME,
                  QAHUB_SUBCTLG.SUBCTLG_ID,QAHUB_SUBCTLG.SUBCTLG_NAME
            FROM QAHUB_SUBCTLG, QAHUB_CTLG 
            WHERE QAHUB_SUBCTLG.CTLG_ID = QAHUB_CTLG.CTLG_ID
            ORDER BY DBMS_RANDOM.VALUE
        ) WHERE ROWNUM = 1;
        
    INSERT INTO QAHUB_QSTN (
                            QSTN_ID, 
                            TITLE,
                            CTLG_ID, 
                            SUBCTLG_ID, 
                            USER_ID, 
                            CONTENT, 
                            STATUS,
                            ENT_DT,
                            UPD_DT,
                            ENT_TMS,
                            UPD_TMS
                            )
                VALUES(
                  SYS_GUID,
                  DBMS_RANDOM.STRING('A',90),
                  V_CTLG_ID,
                  V_SUBCTLG_ID,
                  '100101',
                  DBMS_RANDOM.STRING('A', 100),
                  0,
                  TO_CHAR((SYSTIMESTAMP+100*DBMS_RANDOM.VALUE*DBMS_RANDOM.VALUE), 'YYYY-MM-DD HH24:MI'),
                  TO_CHAR((SYSTIMESTAMP+100*DBMS_RANDOM.VALUE*DBMS_RANDOM.VALUE), 'YYYY-MM-DD HH24:MI'),
                  (SYSTIMESTAMP+100*DBMS_RANDOM.VALUE*DBMS_RANDOM.VALUE),
                  (SYSTIMESTAMP+100*DBMS_RANDOM.VALUE*DBMS_RANDOM.VALUE)
                );
    END LOOP;

    NULL;
  END BATCH_QSTN;

  PROCEDURE BATCH_ANS AS
    V_QSTN_ID VARCHAR2(32);
  BEGIN
  
  FOR LOOP_INDEX IN 1..500 LOOP
    SELECT QSTN_ID INTO V_QSTN_ID
      FROM (SELECT QSTN_ID FROM QAHUB_QSTN ORDER BY DBMS_RANDOM.VALUE)
        WHERE ROWNUM=1;
    
    INSERT INTO QAHUB_ANS(QSTN_ID, ANS_ID, USER_ID, CONTENT)
      VALUES(
        V_QSTN_ID,
        SYS_GUID,
        '100101',
        DBMS_RANDOM.STRING('A',100)
  
      );
  END LOOP;
    NULL;
  END BATCH_ANS;

END PCKG_QAHUB_BATCH;
/
