CREATE OR REPLACE PACKAGE PCKG_QAHUB_CTLG AS

  TYPE CTLG_REC IS RECORD(
    CTLG_ID           VARCHAR2(32),
    CTLG_NAME         VARCHAR2(50)
  );

  TYPE SUBCTLG_REC IS RECORD(
    SUBCTLG_ID        VARCHAR2(32),
    SUBCTLG_NAME      VARCHAR2(50)
  );

  TYPE CTLG_CUR IS REF CURSOR RETURN CTLG_REC;
  TYPE SUBCLTG_CUR IS REF CURSOR RETURN SUBCTLG_REC;

  PROCEDURE PROC_CLTG_QRY(
    OI_FLAG           OUT     INTEGER,
    OS_ERRCODE        OUT     VARCHAR2,
    OS_MSG            OUT     VARCHAR2
  );

  PROCEDURE PROC_SUBCTLG_QRY(
    IS_CTLG_ID        IN      VARCHAR2,
    OI_FLAG           OUT     INTEGER,
    OS_ERRCODE        OUT     VARCHAR2,
    OS_MSG            OUT     VARCHAR2
  );

END PCKG_QAHUB_CTLG;

/



/
