CREATE OR REPLACE PACKAGE PCKG_QAHUB_CTLG AS

  TYPE CTLG_REC IS RECORD(
    CTLG_ID           VARCHAR2(32),
    CTLG_NAME         VARCHAR2(50),
    ENT_TMS           TIMESTAMP
  );

  TYPE SUBCTLG_REC IS RECORD(
    SUBCTLG_ID        VARCHAR2(32),
    SUBCTLG_NAME      VARCHAR2(50),
    CTLG_ID           VARCHAR2(50),
    ENT_TMS           TIMESTAMP
  );

  TYPE CTLG_CUR IS REF CURSOR RETURN CTLG_REC;
  TYPE SUBCLTG_CUR IS REF CURSOR RETURN SUBCTLG_REC;

  PROCEDURE PROC_CTLG_QRY(
    OI_FLAG           OUT     INTEGER,
    OS_ERRCODE        OUT     VARCHAR2,
    OS_MSG            OUT     VARCHAR2,
    OC_CTLG_CUR       OUT     CTLG_CUR
  );

  PROCEDURE PROC_SUBCTLG_QRY(
    IS_CTLG_ID        IN      VARCHAR2,
    OI_FLAG           OUT     INTEGER,
    OS_ERRCODE        OUT     VARCHAR2,
    OS_MSG            OUT     VARCHAR2,
    OC_SUBCTLG_CUR    OUT     SUBCLTG_CUR
  );
  
  PROCEDURE PROC_CTLG_SUBCTLG_QRY(
    IS_CTLG_ID        IN      VARCHAR2,
    OI_FLAG           OUT     INTEGER,
    OS_ERRCODE        OUT     VARCHAR2,
    OS_MSG            OUT     VARCHAR2,
    OC_CTLG_CUR       OUT     CTLG_CUR,
    OC_SUBCTLG_CUR    OUT     SUBCLTG_CUR
  );

END PCKG_QAHUB_CTLG;
/


CREATE OR REPLACE PACKAGE BODY PCKG_QAHUB_CTLG AS

  PROCEDURE PROC_CTLG_QRY(
    OI_FLAG           OUT     INTEGER,
    OS_ERRCODE        OUT     VARCHAR2,
    OS_MSG            OUT     VARCHAR2,
    OC_CTLG_CUR       OUT     CTLG_CUR
  ) AS
  BEGIN

    OI_FLAG := 0;

    OPEN OC_CTLG_CUR FOR
      SELECT CTLG_ID, CTLG_NAME, ENT_TMS
        FROM QAHUB_CTLG;

  EXCEPTION
    WHEN OTHERS THEN
      OI_FLAG     :=-1;
      OS_ERRCODE  :=SQLCODE;
      OS_MSG      :=SQLERRM;
      
  END PROC_CTLG_QRY;

  PROCEDURE PROC_SUBCTLG_QRY(
    IS_CTLG_ID        IN      VARCHAR2,
    OI_FLAG           OUT     INTEGER,
    OS_ERRCODE        OUT     VARCHAR2,
    OS_MSG            OUT     VARCHAR2,
    OC_SUBCTLG_CUR    OUT     SUBCLTG_CUR
  ) AS
  BEGIN
  
    OI_FLAG := 0;

    OPEN OC_SUBCTLG_CUR FOR
      SELECT SUBCTLG_ID,SUBCTLG_NAME,CTLG_ID,ENT_TMS
        FROM QAHUB_SUBCTLG
          WHERE CTLG_ID = IS_CTLG_ID;

  EXCEPTION
    WHEN OTHERS THEN
      OI_FLAG     :=-1;
      OS_ERRCODE  :=SQLCODE;
      OS_MSG      :=SQLERRM;
      
  END PROC_SUBCTLG_QRY;
  
  PROCEDURE PROC_CTLG_SUBCTLG_QRY(
    IS_CTLG_ID        IN      VARCHAR2,
    OI_FLAG           OUT     INTEGER,
    OS_ERRCODE        OUT     VARCHAR2,
    OS_MSG            OUT     VARCHAR2,
    OC_CTLG_CUR       OUT     CTLG_CUR,
    OC_SUBCTLG_CUR    OUT     SUBCLTG_CUR
  ) AS

  BEGIN
    NULL;
  END PROC_CTLG_SUBCTLG_QRY;
  
END PCKG_QAHUB_CTLG;
/
